blank_issues_enabled: true
contact_links:
  - name: âœ‰ï¸ My contacts
    url: https://linktr.ee/BennyExtreme
    about: Open the list of all my contacts
  - name: ğŸ“¥ Download
    url: https://github.com/BennyExtreme/UDPWiiHook/releases/latest/download/UDPWiiHook.exe
    about: Download the latest version of UDPWiiHook
  - name: ğŸ”— Main repository
    url: https://github.com/EZForever/UDPWiiHook
    about: Open the main repository from Eric Zhang (EZForever)
